# Generated by Django 3.1.2 on 2020-12-11 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modalform',
            old_name='massage',
            new_name='message',
        ),
    ]
