# Generated by Django 3.1.2 on 2020-12-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0004_contactform'),
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyContactForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
