# Generated by Django 3.1.2 on 2020-12-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0005_propertycontactform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PropertyContactForm',
            new_name='BiharPropertyContactForm',
        ),
    ]
