# Generated by Django 3.1.2 on 2020-12-11 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0007_patnapropertycontactform'),
    ]

    operations = [
        migrations.AddField(
            model_name='biharpropertycontactform',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='contactform',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='enquiryform',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='modalform',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='patnapropertycontactform',
            name='created',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
