# Generated by Django 3.1.2 on 2020-12-13 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homeapp', '0008_auto_20201211_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('mobile_no', models.IntegerField(null=True)),
                ('filename', models.FileField(upload_to='static/careerfile/')),
                ('message', models.TextField(null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='patnapropertycontactform',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
